### PR TITLE
Add KIOO token

### PR DESCRIPTION
**Pull request by fenicks**

### CODE REVIEW

**Comment by best-coder-NA** [comment]
Re-opened. Please verify the KIOO token on the c-chain explorer for safety

**Comment by best-coder-NA** [comment]
Re-opened. Please verify the KIOO token on the c-chain explorer for safety

**Comment by fenicks** [comment]
Version clash conflict is fixed.

**Comment by fenicks** [comment]
> Thanks! Can we scope this change to only the KIOO token without changing (even formatting) of others in the list please?

Looks OK on github now. vscode didn't show me the changes on formatting.

**Review by best-coder-NA — APPROVED** [review]

**Pull request merged**
