### PR TITLE
Please add Canopus to defi.tokenlist.json

### PR DESCRIPTION
**Pull request by canopus-network**

### CODE REVIEW

**Comment by best-coder-NA** [comment]
More due diligence needed on this project before we can officially add them to our token list

**Comment by bmino** [comment]
hey @canopus-network, adding a new token must be accompanied by a minor version increase as specified in the [semantic versioning guide](https://github.com/Uniswap/token-lists#semantic-versioning)

apologies that these instructions are linked from our README and not yet directly posted there

**Review by canopus-network — COMMENTED** [review]
Fixed

**Comment by bmino** [comment]
@canopus-network thank you!

since AVE was merged first (version 7), the minor version should now be incremented to 8
also, kindly update the timestamp

**Review by canopus-network — COMMENTED** [review]
fixed, please check

**Comment by bmino** [comment]
looks good @canopus-network 

you'll need to fix the merge conflict due to how far back the Canopus-Network-OPUS repo branched from `main`

**Pull request closed without merging**
