### PR TITLE
Added GothicJawa/GOTH Token

### PR DESCRIPTION
**Pull request by GothToken**
Added token, incremented version, updated timestamp.

### CODE REVIEW

**Comment by bmino** [comment]
Please follow the instructions on the README to update the version and timestamp. This is also invalid json missing a comma

**Comment by GothToken** [comment]
Sorry about that, should be fixed and updated now.

**Comment by bmino** [comment]
thank you for updating the timestamp. please update the minor version as per the README. the `tokens` field is still invalid json

**Comment by HariSeldon23** [comment]
Closing due to lack of activity

**Pull request closed without merging**
