### PR TITLE
Update defi.tokenlist.json

### PR DESCRIPTION
**Pull request by MediumSizedWhale**
Updated Spore info

### CODE REVIEW

**Comment by dasconnor** [comment]
you need to bump the revision in the version number

**Comment by MediumSizedWhale** [comment]
This?

`    "version": {
        "major": 2,
        "minor": 0,
        "patch": 0`

**Comment by dasconnor** [comment]
yes, the patch field, sorry

**Review by MediumSizedWhale — COMMENTED** [review]
Bumped patch number to 1

**Review by dasconnor — APPROVED** [review]

**Pull request merged**
