### PR TITLE
Add Jenkem to DefiTokenList

### PR DESCRIPTION
**Pull request by klyed**
Added the new JENKEM token to Pangolin

### CODE REVIEW

**Comment by klyed** [comment]
Hey guys, hopefully I did this right. If not, please let me know how I can improve!~ Thanks!

**Comment by bmino** [comment]
Hey @klyed, the formatting looks good here. Please verify your token contract on the cchain explorer: <https://cchain.explorer.avax.network/address/0xdE61d83F83950fDe967BD2C68B1a9f64694F85Ff>

You'll also want to add your token here with a PR that only addresses your token:
<https://github.com/pangolindex/tokens>

**Comment by klyed** [comment]
Hey man! Thanks for the reply!

I'll have another whack at verification, tried for 2 hours yesterday and couldn't get it. I used Tokenmint.io assuming it would register / verify the token automatically as it does on ETH, sadly it did not, and I've been able to find the correct compiler version / evm version to get the hash to match 100%.. :/

Got it super close, I have the code it's based on after some digging, but cannot for the life of me get the darn thing to verify on the c-chain.. Has anyone else had luck verifying recently created tokenmint.io tokens on AVAX that you know of? I'm at a loss of things to try to verify it.

Source code is here (same site / source I minted the token from):
https://github.com/MerkleBlue/tokenmint/blob/master/flatContracts/FlatTokenMintERC20Token.sol

But for some reason it rejects it. :(

Any help verifying this tokenmint.io token or leads on how I can get it verified on c-chain would be highly appreciated!


Thanks for the reply sir! I'll go add the token to the PR as you directed and try a few more times to verify this token.

cheers! Talk soon.

**Comment by bmino** [comment]
yeah, that is the right path. get the compiled version, contract name, flattened code, and some constructor params. their repo from 2019 isn't configured to use any optimization runs, but I couldn't figure out what tokenmint is actually doing under the hood

**Comment by klyed** [comment]
> yeah, that is the right path. get the compiled version, contract name, flattened code, and some constructor params. their repo from 2019 isn't configured to use any optimization runs, but I couldn't figure out what tokenmint is actually doing under the hood

Bah, yeah I've found 3 different deployed source codes for the "TokenMintERC20Token" that the site uses, but cannot for the damn life of me figure out what magic combo is going to match the bytecode.. The worst part is too, that the expected output  and the generated output is incredibly close, only a few bytes off.

Thank you for your reply and trying to help with your knowledge, going to grab a bite to eat and try to verify here again in a bit.

Cheers captain!

**Comment by bmino** [comment]
Is it an option to deploy the contract via a gui something like https://remix.ethereum.org/ which will generate the required information to easily validate? And will let you deploy with known parameters

**Comment by klyed** [comment]
> Is it an option to deploy the contract via a gui something like https://remix.ethereum.org/ which will generate the required information to easily validate? And will let you deploy with known parameters

Tried again last night but still no luck, trying my hand at reverse engineering the changes.. I'm not sure the code on teh github though they have matches what they deployed. I'll check out your lead though. Thank you captain!

**Pull request closed without merging**
