### PR TITLE
Add aaBLOCK (Blocknet) to DeFi token list

### PR DESCRIPTION
**Pull request by ConanMishler**

### CODE REVIEW

**Comment by dasconnor** [comment]
You need to fix the address capitalization and bump the list version

**Comment by ConanMishler** [comment]
Ok, I think I have the address capitalization fixed and bumped the list version

**Comment by ConanMishler** [comment]
reverted the extra version bump on my PR since addition of Bonfire token was reverted

**Comment by dasconnor** [comment]
Thanks for the tip, I'll add that into the README. Closing this PR in favor of #25

**Pull request closed without merging**
