### PR TITLE
AVE token details

### PR DESCRIPTION
**Pull request by avaware**

### CODE REVIEW

**Comment by bmino** [comment]
hey @avaware, adding a new token should increment the minor version, not the major version as specified by the [upstream semantic versioning guide](https://github.com/Uniswap/token-lists#semantic-versioning)

apologies that this is linked from the README and not directly included

**Comment by avaware** [comment]
thanks, i corrected it now

**Comment by bmino** [comment]
almost there! the minor version should be incremented from 6 to 7

also, kindly update the timestamp

**Comment by avaware** [comment]
my mistake, the minor version was originally 5 so i assumed i would just increment it once to 6, i've incremented it to 7 now! thanks

**Comment by bmino** [comment]
Great, fixed a lil merge conflict with the minor version due to how this was branched and you're all good!

**Pull request merged**
